In [2]:
import tensorflow as tf
print(tf.__version__)

2.9.2


In [3]:
matrix=tf.constant([[10,7,3],[10,7,8],[50,60,70]])
matrix

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10,  7,  3],
       [10,  7,  8],
       [50, 60, 70]], dtype=int32)>

In [4]:
matrix.ndim

2

In [7]:
matrix2=tf.constant([[[30,30,30],[40,40,40]],[[80,90,40],[20,30,40]]])
matrix2

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[30, 30, 30],
        [40, 40, 40]],

       [[80, 90, 40],
        [20, 30, 40]]], dtype=int32)>

In [8]:
matrix2.ndim

3

This file have basic creation of tennsor and there creation.