In [2]:
import tensorflow as tf
random1=tf.random.uniform(shape=[2])

random2=tf.random.uniform(shape=[], minval=-1., maxval=0.)

random3=tf.random.uniform(shape=[], minval=5, maxval=10, dtype=tf.int64)
random1,random2,random3

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.6218568 , 0.91124904], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-0.4411801>,
 <tf.Tensor: shape=(), dtype=int64, numpy=5>)

The seed argument produces a deterministic sequence of tensors across multiple calls. To repeat that sequence, use tf.random.set_seed:

In [3]:
tnsr=tf.Variable([10,20,30])
tf.random.shuffle(tnsr)
tnsr

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([10, 20, 30], dtype=int32)>

here the shuffling is done dimension basis however in single dimension as above the tensor doesn't change

In [4]:
tnsr2=tf.constant([[10,29],[40,50],[47,99]])
tf.random.shuffle(tnsr2)
tnsr2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 29],
       [40, 50],
       [47, 99]], dtype=int32)>

numpy have only arnage not arrange attribute

In [5]:
import numpy as np
arr=np.arange(1,31,dtype=np.int32)
A = tf.constant(arr,  
                shape=[2, 3, 5])
arr,A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30], dtype=int32),
 <tf.Tensor: shape=(2, 3, 5), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15]],
 
        [[16, 17, 18, 19, 20],
         [21, 22, 23, 24, 25],
         [26, 27, 28, 29, 30]]], dtype=int32)>)

here are some functions to know info about your tensor.

In [6]:
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [7]:
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


Tensor have basic opration like +,-,*

In [8]:
x = tf.constant([16, 12, 11])
y = tf.constant([4, 6, 2])
tf.divide(x,y)



<tf.Tensor: shape=(3,), dtype=float64, numpy=array([4. , 2. , 5.5])>

most of them works with .add,.subtract,.multiply,.divide
https://www.tensorflow.org/api_docs/python/tf/math/subtract
here is documentation link for the same.

In [9]:
m1=tf.constant([[10,7],[3,4]])
tf.multiply(m1,m1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

 It doesn't works as a matrix multiplication of sorts.

# for matrix multiplaction we can use a new function
tf.linalg.matmul(a,b)
here linalg is short form of # linear agebra#.

In [10]:
tf.linalg.matmul(m1,m1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [13]:
m1 @ m1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [16]:
m2=tf.constant([[2],[1]])
m1 @ m2

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[27],
       [10]], dtype=int32)>

In [18]:
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [19]:
print("Normal Y:")
print(Y, "\n") # "\n" for newline

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


tf.cast is used to change the dtype of the tensor

In [20]:
B = tf.constant([1.7, 7.4])

# Create a new tensor with default datatype (int32)
C = tf.constant([1, 7])
B, C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>)

In [21]:
B = tf.cast(B, dtype=tf.float16)
C = tf.cast(C, dtype=tf.float32)
B,C

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>)

In [23]:
B= tf.cast(B, dtype=tf.int16)
B

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([1, 7], dtype=int16)>

As shown above the float to int conversion is possible

### Finding the min, max, mean, sum (aggregation)

You can quickly aggregate (perform a calculation on a whole tensor) tensors to find things like the minimum value, maximum value, mean and sum of all the elements.

To do so, aggregation methods typically have the syntax `reduce()_[action]`, such as:
* [`tf.reduce_min()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_min) - find the minimum value in a tensor.
* [`tf.reduce_max()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_max) - find the maximum value in a tensor (helpful for when you want to find the highest prediction probability).
* [`tf.reduce_mean()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_mean) - find the mean of all elements in a tensor.
* [`tf.reduce_sum()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_sum) - find the sum of all elements in a tensor.
* **Note:** typically, each of these is under the `math` module, e.g. `tf.math.reduce_min()` but you can use the alias `tf.reduce_min()`.

Let's see them in action.

Here there is different module for the probability and the variance.

In [24]:
import tensorflow_probability as tfp
tfp.stats.variance(B)

<tf.Tensor: shape=(), dtype=int16, numpy=9>

similarly for the std one must typrcast the tensor into the float32 type